# Dependencies
markdown: redcarpet
highlighter: pygments

plugins:
  - jekyll-maps

# Permalinks
permalink: pretty

# Setup
title: Hyde
tagline: "A Jekyll theme"
description: 'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url: http://hyde.getpoole.com
baseurl: ""

author:
  name: "Mark Otto"
  url: https://twitter.com/mdo

paginate: 5

# Custom vars
version: 2.1.0

github:
  repo: https://github.com/poole/hyde

maps:
  google:
    api_key: AIzaSyDf0evQzrDbLUck2OEJ7FUrzxtw3RUGzX4
location:
  - latitude: 51.5285582
    longitude: -0.2416807
  - latitude: 52.5285582
    longitude: -2.2416807
  - title: custom marker title
    image: custom marker image
    url: custom marker url
    latitude: 51.5285582
    longitude: -0.2416807
